### PR TITLE
SPCFile.cpp: fix detection of ID666 tags

### LINKED ISSUE #610: SFX Discovery
### Environment details

* Operating System+version: **Windows 10 - Unsure of Version**
* VGMTrans version: **Latest Nightly**
* Game ROM/music dump name and sha256: N/A - Self Dump

### Describe the bug

I noticed why some snes songs are not loading, especially for custom SPCs/SFX SPCs
Checking logs, I noticed this error in the log
"invalid stoi argument"

Forgive me for this, my first time actually making a bug report here

### Steps to reproduce

1. Load any self Dumped SPC, or any spc from SMWCentral
2. SPC will fail to load, error is logged

### Expected behaviour

SPC should load

### Additional context

_No response_

### Logs

[error.log](https://github.com/user-attachments/files/20562643/error.log)

<details><summary>Click to expand log</summary>

```
invalid stoi argument
```

</details>

### PR DESCRIPTION
**Pull request by CBongo**
The check for ID666 tags was checking for nonzero value instead of 0x1a; a value of 0x1b indicates no tags, which resulted in std::stoi throwing an exception when reading the  secondsToPlay and fadeLength.  Fixed the check for tags, and wrapped the std::stoi calls with try/catch to protect against the unexpected and allow slightly malformed files to load anyway.

Closes #610 and #626

### CODE REVIEW

File: src/main/components/SPCFile.cpp [hunk 1]
```diff
@@ -28,7 +28,8 @@ SPCFile::SPCFile(const RawFile& file) {
     throw std::runtime_error("Invalid SPC signature");
   }
 
-  m_hasID666Tag = file.readByte(0x23);
+  m_hasID666Tag = file.readByte(0x23) == 0x1a;
+  L_DEBUG("SPC file has ID666 tag? {}", m_hasID666Tag);
```
Comment (sykhro) [inline src/main/components/SPCFile.cpp]: I would argue there is not much value in keeping this debug line

**Review by sykhro — CHANGES_REQUESTED** [review]
Thank you for your contribution! I have one minor comment

**Comment by Bonboon229** [comment]
A longterm issue solved at last!

File: src/main/components/SPCFile.cpp (hunk 1 above)
Comment (CBongo) [reply src/main/components/SPCFile.cpp]: Agreed; removed.  Do you think there would be value in logging something at DEBUG or INFO only in the case where there is no tag?  If so this would be a good time to add it; if not then we should be good to go.  After writing it down I'm leaning towards "no" myself...

**Review by sykhro — APPROVED** [review]

**Comment by mikelow** [comment]
Thanks for the fix!

File: src/main/components/SPCFile.cpp (hunk 1 above)
Comment (sykhro) [reply src/main/components/SPCFile.cpp]: I would say no. Tags are not something that sensitive so I wouldn't bother with logging details of parsing!
