### PR TITLE
Address bank select issues

### LINKED ISSUE #11: [FEATURE REQ] Allow to choose bank select MSB/LSB by preference
Current VGMTrans converts program number 128 to bank MSB=0/LSB=1 program 0. This is arithmetically correct, but many editors/plugins seem to use bank MSB and just ignore bank LSB.

So I hope VGMTrans will swap the bank output.

*Reported by SOU1, thanks.

### LINKED ISSUE #264: Inconsistency in bank select strategy between MIDI data and in-app player
## Case 1

**Describe the bug**
In Qt build, some instruments will not be played or will be played as different instruments. This is caused by a bank strategy mismatch between MIDI data and BASSMIDI.

In general, SeqTrack outputs banks in the "mma" style (CC0*128+CC32) as described in Fluidsynth. Therefore, the MIDI data generated by VGMTrans usually selects a bank using CC32. On the other hand, BASSMIDI seems to expect CC0 as a bank select message. (This seemed to be the case even when XG Reset sysex was sent.)

This did not happen in the WTL version. This is probably because DirectMusic uses DLS, and DLS should be able to set the bank number in MSB/LSB.

**To Reproduce**
Steps to reproduce the problem.
1. Load SNES Donkey Kong Country 2: Klubba's Reveille (dkq-23.spc)
2. The low brass sound is played by a square-like synth (some other instruments also have problems)

Later AKAOs (e.g. Final Fantasy IX) are also good for checking the performance of banked instruments.

## Case 2

The following problem used to occur with Fluidsynth, but no longer occurs after switching to BASSMIDI. Just be careful not to let it happen again in the process of fixing the problem above.

**Describe the bug**
The drum sounds of late SNES AKAO songs don't sound right, but are instead played by a saw-like synth or something.

In this case, the bank number of the drum is defined as `(127 << 14)`, so VGMTrans will output bank MSB=127 to the MIDI data.

**To Reproduce**
Steps to reproduce the problem.
1. Load the Battle theme from Chrono Trigger (ct-112.spc), for example
    * In addition to Chrono Trigger, the same problem can be seen in Romancing SaGa 3 and Gun Hazard
2. The drum sounds such as snares are played by a saw-like synth

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans version: e579b9c, master
 - VGMTrans log: No errors or warnings
 - Game ROM or music dump SHA-256: [Super Donkey Kong 2: Dixie & Diddy ~ SNESmusic.org](http://snesmusic.org/v2/profile.php?profile=set&selected=15924)
 - Game ROM or music dump SHA-256: [Chrono Trigger ~ SNESmusic.org](http://snesmusic.org/v2/profile.php?selected=554&profile=set)

### PR DESCRIPTION
**Pull request by sykhro**
Fixes a long standing issue with the format of the bank selects we use.

## Description
Details are in #264.
This adds support for GS and MMA style bank selection. Perhaps GM and XG could be handy too?

## Motivation and Context
Fixes #264, fixes #11

## How Has This Been Tested?
By playing back various songs and checking the MIDI output.

## Screenshots (if appropriate):
Appearance of the selector (only tested on macOS)
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/main/SeqTrack.cpp [hunk 1]
```diff
@@ -1203,17 +1203,27 @@ void SeqTrack::AddProgramChange(uint32_t offset,
...
   }
 }
 
 void SeqTrack::AddBankSelectNoItem(uint8_t bank) {
   if (readMode == READMODE_CONVERT_TO_MIDI) {
-    pMidiTrack->AddBankSelect(channel, bank / 128);
-    pMidiTrack->AddBankSelectFine(channel, bank % 128);
+    if (auto style = ConversionOptions::the().GetBankSelectStyle();
+        style == BankSelectStyle::GS) {
+      pMidiTrack->AddBankSelect(channel, bank >> 7);
```
Comment (loveemu) [inline src/main/SeqTrack.cpp:1222]:
```suggestion
      pMidiTrack->AddBankSelect(channel, bank & 0x7f);
```

**Comment by loveemu** [comment]
Thanks for the nice changes. ❤️ 

* MIDI+DLS playback in the "GS" style is problematic because the bank options are not reflected in the DLS bank numbers. Also, since GS style is internally selected as the default value, the DirectMusic output of the WTL version is affected by this.

**Comment by sykhro** [comment]
> Thanks for the nice changes. ❤️
> 
>     * MIDI+DLS playback in the "GS" style is problematic because the bank options are not reflected in the DLS bank numbers. Also, since GS style is internally selected as the default value, the DirectMusic output of the WTL version is affected by this.
> 
>     * UI: Initially, none of the bank styles are selected.

I have hard-coded WTL to use the MMA-style bank-select, so that it will keep working as it always has (this means it will continue outputting MIDIs with MMA bs, but it has been doing so for years so I'd say it's fine to keep it this way).
As for the UI, I can't reproduce; the code for the default selection is [here](https://github.com/vgmtrans/vgmtrans/pull/298/files#diff-33e6393e424821922e6b7e8998740cc8b7898960589eb8ce57019fb006c1edb9R39)

**Comment by loveemu** [comment]
Thank you. It worked.

Is it outside the scope of this PR to reflect the bank number preference in the DLS export?
I'm sorry for making you do so many things. I just want to keep track of everything I notice, so there's no need to rush.

**Comment by sykhro** [comment]
> Thank you. It worked.
> 
> Is it outside the scope of this PR to reflect the bank number preference in the DLS export? I'm sorry for making you do so many things. I just want to keep track of everything I notice, so there's no need to rush.

No worries! I'm not sure what you mean, is it something that needs to change in DLSFile?

**Comment by sykhro** [comment]
I did it, not 100% sure if it is correct

File: src/main/VGMColl.cpp [hunk 2]
```diff
@@ -196,7 +197,19 @@ bool VGMColl::MainDLSCreation(DLSFile &dls) {
...
+      * The ulBank field follows this structure:
+      * F|00000000000000000|CC0|CC32
+      * where F = 0 if the instrument is melodic, 1 otherwise
+      * (length of each CC is 7 bits, obviously)
+      */
+      if (auto bs = ConversionOptions::the().GetBankSelectStyle(); bs == BankSelectStyle::GS) {
+        bank_no = bank_no << 7;
+      } else if (bs == BankSelectStyle::MMA) {
+        bank_no = ((bank_no / 128) << 7) | bank_no;
+      }
```
Comment (loveemu) [inline src/main/VGMColl.cpp:211]:
```suggestion
      auto bank_no = vgminstr->bank;
      /*
      * The ulBank field follows this structure:
      * F|00000000000000000|CC0|0|CC32
      * where F = 0 if the instrument is melodic, 1 otherwise
      * (length of each CC is 7 bits, obviously)
      */
      if (auto bs = ConversionOptions::the().GetBankSelectStyle(); bs == BankSelectStyle::GS) {
        bank_no &= 0x7f;
        bank_no = bank_no << 8;
      } else if (bs == BankSelectStyle::MMA) {
        const uint8_t bank_msb = (bank_no >> 7) & 0x7f;
        const uint8_t bank_lsb = bank_no & 0x7f;
        bank_no = (bank_msb << 8) | bank_lsb;
      }
```

The incorrect description of `ulBank` confused me a lot. 😞

With this change, I believe `VGMInstr` will have the same internal MMA-style bank number as `VGMSeq`, and map it properly during DLS export.

Before the change, the bank number of `VGMInstr` used the same format as the bank number of DLS. However, upon investigation, it turned out that only a small bank number was actually being used, and only `AkaoSnesDrumKit` was intentionally trying to use bank MSB.

I will fix bank mapping in AkaoSnesDrumKit in another comment.

Comment (loveemu) [reply src/main/VGMColl.cpp:211]: I wasn't sure where best to comment, so I'll post a diff here to fix the bank number for AkaoSnesDrumKit.

```diff
 src/main/formats/AkaoSnesInstr.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/main/formats/AkaoSnesInstr.cpp b/src/main/formats/AkaoSnesInstr.cpp
index a0d9a59..04ba393 100644
--- a/src/main/formats/AkaoSnesInstr.cpp
+++ b/src/main/formats/AkaoSnesInstr.cpp
@@ -154,7 +154,7 @@ AkaoSnesDrumKit::AkaoSnesDrumKit(VGMInstrSet *instrSet,
                                  uint16_t addrADSRTable,
                                  uint16_t addrDrumKitTable,
                                  const std::wstring &name) :
-  VGMInstr(instrSet, addrTuningTable, 0, ((programNum >> 6) & 0x7F00) | ((programNum >> 7) & 0x7F), programNum & 0xFF, name), version(ver),
+  VGMInstr(instrSet, addrTuningTable, 0, programNum >> 7, programNum & 0x7F, name), version(ver),
   spcDirAddr(spcDirAddr),
   addrTuningTable(addrTuningTable),
   addrADSRTable(addrADSRTable),
 src/main/formats/AkaoSnesInstr.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/main/formats/AkaoSnesInstr.h b/src/main/formats/AkaoSnesInstr.h
index 0b48c3c..8b9d259 100644
--- a/src/main/formats/AkaoSnesInstr.h
+++ b/src/main/formats/AkaoSnesInstr.h
@@ -11,7 +11,7 @@
 class AkaoSnesInstrSet:
     public VGMInstrSet {
  public:
-  static const uint32_t DRUMKIT_PROGRAM = (0x7F << 14);
+  static const uint32_t DRUMKIT_PROGRAM = (0x7F << 7);
 
   AkaoSnesInstrSet(RawFile *file,
                    AkaoSnesVersion ver,
```

Before the change, bank MSB=127 was used, but after the change, bank LSB=127 will be used for the MMA style. It might be possible to abstract "bank for drums" so that it always prefers bank MSB=127, but for now we simply focused on fixing the bank number mismatch.

Comment (sykhro) [reply src/main/VGMColl.cpp]: Thank you for the review, will add this.
